apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  generation: 1
  labels:
    app: kibana
  name: kibana
  namespace: logging
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: hkube-sys-kibana
          servicePort: 5601
        path: /system/kibana(/|$)(.*)
status:
  loadBalancer: {}
