apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  name: provisioner
spec:
  finalizers:
  - kubernetes
